### ISSUE TITLE
deprecated error

### ISSUE THREAD

**Issue by jodyngo** [ChaoticConundrum/libchaos#3]
please advise me how to fix this error
h264_modify/h264-roi/zh264decoder.cpp:149:15: warning: ‘int avcodec_decode_video2(AVCodecContext*, AVFrame*, int*, const AVPacket*)’ is deprecated [-Wdeprecated-declarations]

**Comment by ChaoticEnigma** [comment]
Pretty much what it says, the `avcodec_decode_video2` function probably has `__attribute__ ((deprecated))`. This isn't an error. Also, this issue should be in [h264-roi](https://github.com/ChaoticConundrum/h264-roi).
