### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by jodyngo** [ChaoticConundrum/libchaos#4]
Please advise me this error with many thanks

[ 93%] Linking CXX executable h264_roi
CMakeFiles/h264_roi.dir/zh264encoder.cpp.o: In function `LibChaos::ZH264Encoder::open(LibChaos::ZPath)':
zh264encoder.cpp:(.text+0x641): undefined reference to `x264_encoder_open_152'
collect2: error: ld returned 1 exit status
CMakeFiles/h264_roi.dir/build.make:152: recipe for target 'h264_roi' failed
make[2]: *** [h264_roi] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/h264_roi.dir/all' failed
make[1]: *** [CMakeFiles/h264_roi.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ChaoticEnigma** [comment]
A quick look at the `x264.h` header shows that `x264_encoder_open` is a macro that expands to `x264_encoder_open_##X264_BUILD` to force this exact error. It means your x264 headers and library are not compatible. Make sure you are including the correct `x264.h` which was packaged with your `libx264.a / libx264.so / libx264.dll`. This issue should also be on the [h264-roi](https://github.com/ChaoticConundrum/h264-roi) repo.
